'use client';

import React from 'react';
import { useRouter } from 'next/navigation';
import { useSearchParams } from 'next/navigation';
import { TourEngine } from './TourEngine';
import type { TourStep } from './TourEngine';
import { ExecutiveClientWrapper } from '@/components/dashboard/executive/ExecutiveClientWrapper';

export const executiveSteps: TourStep[] = [
    {
        title: 'Your Organisation at a Glance',
        content: 'This is the Executive Dashboard — your organisation\'s psychological state in a single view. The LIVE badge means data is drawn from real weekly pulses. DEMO MODE means you\'re viewing synthetic representative data. The organisation name and reporting period are shown in the header.',
        targetSelector: '[data-tutorial="executive-header"]',
    },
    {
        title: 'The Four Indices',
        content: 'These four cards represent the core dimensions of organisational health: Strain (cognitive and workload pressure), Withdrawal Risk (disengagement and intent to leave), Trust Gap (perceived safety and leadership trust), and Engagement (active participation and ownership). Values are on a 0–100 scale — higher Strain and Withdrawal are adverse signals, higher Engagement is positive.',
        targetSelector: '[data-tutorial="executive-kpis"]',
    },
    {
        title: 'Interactive Dimension Switching',
        content: 'Click any KPI card to change the chart dimension below. The chart will update to show the 12-week trend for the selected index. The trend arrow on each card shows the week-over-week delta. This interactive selection lets you drill into whichever index is driving your current concern.',
    },
    {
        title: 'Reading the Trend',
        content: 'The chart shows 12 weeks of historical data for the selected index. The shaded band around the line is the model\'s confidence interval — wider bands indicate more uncertainty, typically from lower response rates or high within-team variance. Narrow bands mean the signal is reliable. A rising Strain line with a narrowing band is a high-confidence adverse signal.',
        targetSelector: '[data-tutorial="executive-chart"]',
    },
    {
        title: 'Team Portfolio Status',
        content: 'Every team in your organisation is listed here with their current risk classification. Critical (red) means delivery is at immediate risk — the model has detected sustained high strain or withdrawal above the intervention threshold. At Risk (amber) means deterioration is in progress. Healthy (green) means indices are within normal operating range. Click any team row to drill into their dashboard.',
        targetSelector: '[data-tutorial="executive-portfolio"]',
    },
    {
        title: 'Systemic vs. Local Drivers',
        content: 'The Systemic Drivers panel identifies root causes that span multiple teams or originate in structural conditions — role ambiguity, dependency overload, resource misallocation. These cannot be resolved at the team level alone. Systemic drivers are flagged separately from team-local issues so executive attention is directed to levers that actually move the needle.',
        targetSelector: '[data-tutorial="executive-drivers"]',
    },
    {
        title: 'Escalation Watchlist',
        content: 'The Watchlist surfaces teams or individuals whose signal trajectory requires direct intervention within the current reporting cycle. Severity is computed by combining the rate of change, current index value, and confidence band. A team with rapidly increasing withdrawal and narrowing confidence bands will surface here before it appears in portfolio status as Critical.',
        targetSelector: '[data-tutorial="executive-watchlist"]',
    },
    {
        title: 'Board-Ready Briefing',
        content: 'The Briefing section is generated by a language model fine-tuned on organisational psychology literature. It synthesises the full 48-dimensional signal vector into a narrative suitable for board preparation, stakeholder communication, or management review. It is generated fresh every Monday from the latest model inference run — not summarised from previous text.',
        targetSelector: '[data-tutorial="executive-briefing"]',
    },
    {
        title: 'Data Governance & Coverage',
        content: 'The Data Governance section reports the statistical quality of the data underlying every index and briefing above. Coverage shows the response rate across the organisation. Data Quality reflects internal consistency checks. Total sessions and the last-updated timestamp let you verify recency. These metrics are especially important when presenting to the board — they establish the credibility of the signal.',
        targetSelector: '[data-tutorial="executive-governance"]',
    },
];

export function TutorialExecutive() {
    const router = useRouter();
    const searchParams = useSearchParams();
    const returnTo = searchParams.get('returnTo') || '/tutorial';

    return (
        <>
            <div className="w-full bg-[#050505] min-h-screen">
                {/* Pass null to force demo fallback */}
                <ExecutiveClientWrapper initialData={null as any} />
            </div>
            <TourEngine steps={executiveSteps} onComplete={() => router.push(returnTo)} />
        </>
    );
}
