'use client';

import React from 'react';
import { useRouter } from 'next/navigation';
import { useSearchParams } from 'next/navigation';
import { TourEngine } from './TourEngine';
import type { TourStep } from './TourEngine';
import { TeamClientWrapper } from '@/components/dashboard/team/TeamClientWrapper';

export const teamleadSteps: TourStep[] = [
    {
        title: 'Your Team in Context',
        content: 'The breadcrumb header shows your team in the context of the full organisation. The back arrow navigates to the Executive Dashboard — important for when you need to see where your team sits relative to others. The DEMO badge confirms this is representative data. Your team name and org name are always visible here so stakeholders know exactly which unit they\'re reviewing.',
        targetSelector: '[data-tutorial="team-header"]',
    },
    {
        title: 'Team-Scoped Indices',
        content: 'These four KPI cards show the same dimensions as the Executive view — Strain, Withdrawal Risk, Trust Gap, and Engagement — but scoped to this specific team. A team may be amber on Strain while the org is green overall, which is precisely why this drill-down exists. The trend arrows show week-over-week direction for this team specifically.',
        targetSelector: '[data-tutorial="team-kpis"]',
    },
    {
        title: 'Team Trend Over Time',
        content: 'The chart shows the 12-week history of the selected index for this team. Clicking any KPI card above changes the dimension displayed. Use this view to identify inflection points — weeks where the trend changed direction — and correlate them with delivery events, team changes, or external pressures.',
        targetSelector: '[data-tutorial="team-chart"]',
    },
    {
        title: 'Internal Driver Analysis',
        content: 'The Drivers panel identifies the internal causal factors pushing indices in their current direction. These are team-local structural issues — lack of role clarity, high dependency on blocked external teams, communication friction, or cognitive overload patterns. Each driver is ranked by its inferred contribution to the observed strain or withdrawal signal. Click a driver to expand its detail and see which sub-dimensions are most affected.',
        targetSelector: '[data-tutorial="team-drivers"]',
    },
    {
        title: 'Targeted Interventions',
        content: 'Actions are generated by the system based on the specific driver profile of this team this week. They are not generic advice — each action corresponds to a need state (N0 to N3) determined by the latent state model. N0 means no intervention needed. N3 means the need is critical and the suggested action is high-urgency. Gated actions appear greyed out until prerequisite conditions are met.',
        targetSelector: '[data-tutorial="team-actions"]',
    },
    {
        title: 'Using the Briefing for 1:1s',
        content: 'The Team Briefing is your weekly narrative summary — generated fresh every Monday from the same inference run that produced the KPI cards. It contains the talking points most relevant to this team\'s current state. Use it directly in your 1:1s and retrospectives: share it as context, read specific sections, or use it to structure the agenda. It replaces gut-feel with model-grounded language.',
        targetSelector: '[data-tutorial="team-briefing"]',
    },
    {
        title: 'Data Governance & Signal Confidence',
        content: 'The Data Governance panel shows the statistical backbone of the briefing you just read. Coverage indicates what percentage of your team submitted their pulse this week — low coverage means wider confidence bands. Data Quality, Temporal Stability, and Signal Confidence are quality metrics the model uses internally. If any metric drops below threshold, the briefing will flag reduced reliability. The session count and last-updated timestamp let you verify data freshness.',
        targetSelector: '[data-tutorial="team-governance"]',
    },
];

export function TutorialTeamlead() {
    const router = useRouter();
    const searchParams = useSearchParams();
    const returnTo = searchParams.get('returnTo') || '/tutorial';

    return (
        <>
            <div className="w-full bg-[#050505] min-h-screen">
                {/* teamId="product" forces the demo fallback team */}
                <TeamClientWrapper teamId="product" initialData={null as any} />
            </div>
            <TourEngine steps={teamleadSteps} onComplete={() => router.push(returnTo)} />
        </>
    );
}
